name: Testes


on: [push, pull_request]


env:
  HOST: 127.0.0.1
  MYSQL_DATABASE: bd
  MYSQL_ROOT_PASSWORD: 123


jobs:
  testar-apis:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4


      - name: Pegar dotineti
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'


      - name: Inicializacao
        working-directory: src/services/bd
        run: docker compose up -d --build --wait
        

      - name: Teste-Servico-BD
        working-directory: src/services/bd
        run: dotnet run